import './globals.css'
import { Inter } from 'next/font/google'

import { AddressProvider } from '@/context/AddressContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AddressProvider>
          <div id="wallet-connect-modal" />
          {children}
        </AddressProvider>
      </body>
    </html>
  ); 
}
